baseurl = "http://localhost:1313/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10

[frontmatter]
lastmod = [":git", "lastmod", "date", "publishDate"]

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel = "sitemap"

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "30s"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[taxonomies]
contributor = "contributors"

[permalinks]
blog = "/blog/:title/"

[minify.tdewolff.html]
keepWhitespace = true

[module]
[module.hugoVersion]
extended = true
min = "0.101.0"
max = ""
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "static"
target = "static"
[[module.mounts]]
source = "node_modules/flexsearch"
target = "assets/js/vendor/flexsearch"
[[module.mounts]]
source = "node_modules/katex"
target = "assets/js/vendor/katex"
[[module.mounts]]
source = "node_modules/mermaid"
target = "assets/js/vendor/mermaid"
