defaultMarkdownHandler = "goldmark"

[goldmark]
[goldmark.extensions]
linkify = false
[goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"
[goldmark.parser.attribute]
block = true
title = true
[goldmark.renderer]
unsafe = true

[highlight]
lineNos = false
lineNumbersInTable = true
anchorLineNos = false
lineAnchors = ""
lineNoStart = 1
hl_Lines = ""
style = "dracula"
noClasses = true
tabWidth = 4
guessSyntax = false

[tableOfContents]
startLevel = 2
endLevel = 3
ordered = false
